### ISSUE TITLE
As a use i want search for Cases, using date/state/tribunal as delimetors

### ISSUE THREAD

**Issue by eleloya23** [acrogenesis/BuzonLegal#2]

**Comment by eleloya23** [comment]
osease, que funcione lo de advanced search

**Comment by PatoBeltran** [comment]
We should also consider to populate the `select` fields based not on all the info of the country but on the info available in the system.

**Comment by eleloya23** [comment]
Yes, that's actually a must.

What it is on the select fields is only dummy data.

It should be populated with real data.

**Comment by PatoBeltran** [comment]
@acrogenesis @eleloya  done in PR
