### ISSUE TITLE
As a user i want to see a Status service

### ISSUE THREAD

**Issue by eleloya23** [acrogenesis/BuzonLegal#5]
This view must be connected with the Incidents table and the States table.

Incidents has a list of incidents with date and description
States knows if a given state is online and the last time it was online.

Right now, whats important is that it uses this information directly.

Don't worry about how we are gonna populate that data yet.

**Comment by PatoBeltran** [comment]
working on this

**Comment by PatoBeltran** [comment]
done

**Comment by eleloya23** [comment]
Quitarle las horas, segundos, minutos. Y que este en español la fecha

**Comment by PatoBeltran** [comment]
done... @eleloya @acrogenesis
